title: "The Forward Horizon"
  description: "Structured Living Communities - Building Foundations for 
  Success"
  baseurl: "/the-forward-horizon"
  url: "https://jumaanebey.github.io"

  markdown: kramdown
  highlighter: rouge
  permalink: pretty

  plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

  author:
    name: "The Forward Horizon"
    email: "info@theforwardhorizon.com"

  contact:
    phone: "(555) FORWARD"
    email: "info@theforwardhorizon.com"

  exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
